import React, { useState, useEffect, useRef } from 'react';
import { useAppContext } from '../context/AppContext';

export default function AIGeneratorModal({ isOpen, onClose }) {
  const {
    assets,
    setAssets,
    activeWorkspaceId,
    activeFolderId,
    accentColor
  } = useAppContext();

  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedAsset, setGeneratedAsset] = useState(null);
  const inputRef = useRef(null);

  useEffect(() => {
    if (isOpen) {
      setTimeout(() => inputRef.current?.focus(), 100);
      setPrompt('');
      setGeneratedAsset(null);
      setIsGenerating(false);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleGenerate = (e) => {
    e.preventDefault();
    if (!prompt.trim()) return;

    setIsGenerating(true);
    setGeneratedAsset(null);

    // Simulate AI delay
    setTimeout(() => {
      const lowerPrompt = prompt.toLowerCase();
      let newAsset = {
        name: prompt.substring(0, 30),
        type: 'code',
        value: '',
        tags: 'ai-generated'
      };

      if (lowerPrompt.includes('rocket') || lowerPrompt.includes('spaceship')) {
        newAsset.type = 'svg';
        newAsset.name = 'Rocket Icon';
        newAsset.value = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z"></path><path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z"></path><path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0"></path><path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5"></path></svg>`;
      } else if (lowerPrompt.includes('heart')) {
        newAsset.type = 'svg';
        newAsset.name = 'Heart Icon';
        newAsset.value = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg>`;
      } else if (lowerPrompt.includes('button')) {
        newAsset.type = 'code';
        newAsset.name = 'Tailwind Button';
        newAsset.value = `<button class="px-4 py-2 bg-[var(--accent)] hover:opacity-90 text-white font-semibold rounded-lg shadow-md transition-all active:scale-95">\n  Click Me\n</button>`;
      } else if (lowerPrompt.includes('card')) {
        newAsset.type = 'code';
        newAsset.name = 'Glassmorphism Card';
        newAsset.value = `<div class="p-6 bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl shadow-xl">\n  <h3 class="text-xl font-bold text-slate-800">Glass Card</h3>\n  <p class="text-slate-500 mt-2">Generated by VectorSpace AI.</p>\n</div>`;
      } else if (lowerPrompt.includes('color') || lowerPrompt.includes('red') || lowerPrompt.includes('blue')) {
        newAsset.type = 'color';
        newAsset.name = 'Generated Color';
        newAsset.value = lowerPrompt.includes('red') ? '#ef4444' : lowerPrompt.includes('blue') ? '#3b82f6' : '#8b5cf6';
      } else if (lowerPrompt.includes('pen') || lowerPrompt.includes('edit')) {
        newAsset.type = 'svg';
        newAsset.name = 'Pen Icon';
        newAsset.value = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 20h9"></path><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path></svg>`;
      } else if (lowerPrompt.includes('svg') || lowerPrompt.includes('icon')) {
        newAsset.type = 'svg';
        newAsset.name = 'Generated Icon';
        newAsset.value = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>`;
      } else {
        // Default generic code response
        newAsset.type = 'code';
        newAsset.name = 'Generated Snippet';
        newAsset.value = `<div class="p-4 border rounded-xl">\n  <!-- Generated content for: ${prompt} -->\n  <p>Hello World</p>\n</div>`;
      }

      setGeneratedAsset(newAsset);
      setIsGenerating(false);
    }, 1500);
  };

  const handleSaveToWorkspace = () => {
    if (!generatedAsset) return;
    const assetToSave = {
      ...generatedAsset,
      id: `asset-${Date.now()}`,
      workspaceId: activeWorkspaceId,
      folderId: activeFolderId,
      isPinned: false,
      notes: 'Generated via AI Prompt.',
      history: [],
      lastModified: new Date().toISOString()
    };
    setAssets(prev => [assetToSave, ...prev]);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm" onClick={onClose} />
      
      <div className="relative w-full max-w-2xl bg-white dark:bg-slate-900 rounded-3xl shadow-2xl border border-slate-200 dark:border-slate-700/50 overflow-hidden flex flex-col animate-[fadeInScale_0.2s_ease-out]">
        <style>{`
          @keyframes fadeInScale {
            from { opacity: 0; transform: scale(0.95) translateY(10px); }
            to { opacity: 1; transform: scale(1) translateY(0); }
          }
          @keyframes aiPulse {
            0% { box-shadow: 0 0 0 0 var(--accent-light); }
            70% { box-shadow: 0 0 0 10px rgba(0,0,0,0); }
            100% { box-shadow: 0 0 0 0 rgba(0,0,0,0); }
          }
        `}</style>
        
        {/* Header */}
        <div className="flex items-center justify-between p-4 md:p-6 border-b border-slate-100 dark:border-slate-800">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-xl bg-[var(--accent-light)] flex items-center justify-center text-[var(--accent)]" style={{ '--accent-light': accentColor + '22', '--accent': accentColor }}>
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"></path><path d="M5 3v4"></path><path d="M19 17v4"></path><path d="M3 5h4"></path><path d="M17 19h4"></path></svg>
            </div>
            <div>
              <h2 className="text-xl font-black text-slate-800 dark:text-slate-100">AI Asset Generator</h2>
              <p className="text-xs text-slate-500 font-medium">Generate code, colors, and SVGs instantly from text.</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 rounded-full hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
          </button>
        </div>

        {/* Body */}
        <div className="p-6">
          <form onSubmit={handleGenerate} className="relative">
            <input
              ref={inputRef}
              type="text"
              placeholder="E.g. 'A blue glassmorphism tailwind card' or 'Rocket SVG icon'"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              className="w-full bg-slate-50 dark:bg-slate-800/50 border-2 border-slate-200 dark:border-slate-700 rounded-2xl pl-5 pr-32 py-4 text-sm md:text-base text-slate-800 dark:text-slate-100 font-medium focus:outline-none focus:border-[var(--accent)] transition-all shadow-inner"
              disabled={isGenerating}
            />
            <div className="absolute right-2 top-2 bottom-2">
              <button
                type="submit"
                disabled={isGenerating || !prompt.trim()}
                className="h-full px-6 bg-[var(--accent)] hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed text-white text-sm font-bold rounded-xl transition-all shadow-md active:scale-95 flex items-center space-x-2"
                style={{ backgroundColor: accentColor }}
              >
                {isGenerating ? (
                  <span className="flex items-center space-x-2">
                    <svg className="animate-spin" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 12a9 9 0 1 1-6.219-8.56"></path></svg>
                    <span>Thinking...</span>
                  </span>
                ) : (
                  <span>Generate</span>
                )}
              </button>
            </div>
          </form>

          {/* Results Area */}
          <div className="mt-6 min-h-[160px] flex flex-col justify-center border-2 border-dashed border-slate-200 dark:border-slate-800 rounded-2xl p-6 bg-slate-50/50 dark:bg-slate-900/20">
            {!generatedAsset && !isGenerating ? (
              <div className="text-center">
                <p className="text-sm text-slate-400 font-medium">Results will appear here.</p>
                <div className="mt-4 flex flex-wrap justify-center gap-2">
                  <span onClick={() => setPrompt('Tailwind primary button')} className="cursor-pointer text-[10px] font-bold uppercase tracking-wider bg-slate-100 dark:bg-slate-800 text-slate-500 px-3 py-1.5 rounded-full hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors">Tailwind Button</span>
                  <span onClick={() => setPrompt('Heart SVG icon')} className="cursor-pointer text-[10px] font-bold uppercase tracking-wider bg-slate-100 dark:bg-slate-800 text-slate-500 px-3 py-1.5 rounded-full hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors">Heart SVG</span>
                  <span onClick={() => setPrompt('Glassmorphism card code')} className="cursor-pointer text-[10px] font-bold uppercase tracking-wider bg-slate-100 dark:bg-slate-800 text-slate-500 px-3 py-1.5 rounded-full hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors">Glassmorphism Card</span>
                </div>
              </div>
            ) : isGenerating ? (
              <div className="flex flex-col items-center justify-center space-y-4">
                <div className="w-12 h-12 rounded-full bg-[var(--accent)]/20 flex items-center justify-center" style={{ animation: 'aiPulse 1.5s infinite' }}>
                  <svg className="text-[var(--accent)] animate-bounce" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"></path></svg>
                </div>
                <p className="text-xs text-[var(--accent)] font-bold animate-pulse">Synthesizing design asset...</p>
              </div>
            ) : generatedAsset ? (
              <div className="animate-[fadeInScale_0.3s_ease-out] flex flex-col space-y-4 w-full">
                <div className="flex justify-between items-center">
                  <div className="flex items-center space-x-2">
                    <span className="text-[10px] font-black uppercase tracking-wider bg-emerald-100 text-emerald-600 dark:bg-emerald-900/30 dark:text-emerald-400 px-2 py-0.5 rounded-full">{generatedAsset.type} generated</span>
                    <span className="text-sm font-bold text-slate-700 dark:text-slate-200">{generatedAsset.name}</span>
                  </div>
                </div>
                <div className="w-full flex flex-col md:flex-row gap-4">
                  {/* Visual Preview */}
                  <div className="flex-1 min-h-[120px] md:min-h-[150px] flex items-center justify-center bg-slate-100 dark:bg-slate-800/50 rounded-xl overflow-hidden border border-slate-200 dark:border-slate-700 relative">
                    {generatedAsset.type === 'color' && (
                      <div className="w-full h-full absolute inset-0 flex items-center justify-center" style={{ backgroundColor: generatedAsset.value }}>
                        <span className="font-mono text-sm font-black bg-black/20 text-white px-3 py-1 rounded-lg backdrop-blur-sm">{generatedAsset.value}</span>
                      </div>
                    )}
                    {generatedAsset.type === 'svg' && (
                      <div className="text-[var(--accent)] transition-transform hover:scale-110" dangerouslySetInnerHTML={{ __html: generatedAsset.value.replace(/width="[^"]*"/, 'width="64"').replace(/height="[^"]*"/, 'height="64"') }} />
                    )}
                    {generatedAsset.type === 'code' && (
                      <div className="w-full h-full p-4 flex items-center justify-center overflow-auto" dangerouslySetInnerHTML={{ __html: generatedAsset.value }} />
                    )}
                  </div>
                  
                  {/* Code Payload */}
                  <div className="flex-1 bg-slate-950 rounded-xl p-4 overflow-x-auto h-[120px] md:h-[150px] overflow-y-auto custom-scrollbar">
                    <pre className="text-[10px] text-emerald-400 font-mono leading-relaxed">{generatedAsset.value}</pre>
                  </div>
                </div>

                <div className="flex justify-end pt-2">
                  <button
                    onClick={handleSaveToWorkspace}
                    className="flex items-center space-x-2 bg-slate-800 hover:bg-slate-900 text-white text-xs font-bold py-2.5 px-5 rounded-xl transition-all shadow-md active:scale-95"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="17 8 12 3 7 8"></polyline><line x1="12" y1="3" x2="12" y2="15"></line></svg>
                    <span>Save to Workspace</span>
                  </button>
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  );
}
